[package]
name = "slack-wasi"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Slack extension for flows.network"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
http_req_wasi = "0.10"
slack-flows = { path = "../slack-sdk" }
